server:
  port: 8080
  servlet:
    context-path: /books

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/documentweb"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600000 # in second
  refreshable-duration: 36000 # in seconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persistAuthorization: true
    tryItOutEnabled: true
    csrf.enabled: true
    operationsSorter: method
    tags-sorter: alpha

avatar:
  upload-dir: uploads/avatars

file:
  upload-dir: file:///C:/Users/Anh/OneDrive/Desktop/identity-service/uploads/
  path: http://localhost:8080/books/file/

openai:
  gemini:
    apiKey: ${YOUR_API_KEY_GEMINI}
    model: gemini-1.5-flash-latest:generateContent
    url: https://generativelanguage.googleapis.com/v1beta/models/

app:
  config:
    dataStoragePath: D:\books

